" Author: Alan Chen
" Alan's vimrc.
" This is a helpful resource:
" https://gist.github.com/romainl/9ecd7b09a693816997ba

" Sourcing
source $HOME/.vim/init/plug.vimrc      " plugin loader
source $HOME/.vim/init/general.vimrc   " general settings
source $HOME/.vim/init/mappings.vimrc  " key mappings
source $HOME/.vim/init/functions.vimrc " custom functions
source $HOME/.vim/init/plugins.vimrc   " plugin specific settings

